import type { ModelInfo } from "../model.js"

/**
 * OpenAI Codex Provider
 *
 * This provider uses OAuth authentication via ChatGPT Plus/Pro subscription
 * instead of direct API keys. Requests are routed to the Codex backend at
 * https://chatgpt.com/backend-api/codex/responses
 *
 * Key differences from openai-native:
 * - Uses OAuth Bearer tokens instead of API keys
 * - Subscription-based pricing (no per-token costs)
 * - Limited model subset available
 * - Custom routing to Codex backend
 */

export type OpenAiCodexModelId = keyof typeof openAiCodexModels

// kilocode_change start: ChatGPT subscription catalog defaults and fixed context budget
// Keep the context budget independent of the values advertised by the remote
// Codex catalog. This is the user's fixed safety limit for every Plus/Pro model.
export const OPENAI_CODEX_CONTEXT_WINDOW = 370_000

export const openAiCodexDefaultModelId: OpenAiCodexModelId = "gpt-5.6-sol"
// kilocode_change end

/**
 * Models available through the Codex OAuth flow.
 * These models are accessible to ChatGPT Plus/Pro subscribers.
 * Costs are 0 as they are covered by the subscription.
 */
export const openAiCodexModels = {
	// kilocode_change start: current ChatGPT Plus/Pro Codex fallback catalog
	"gpt-5.6-sol": {
		maxTokens: 128000,
		contextWindow: OPENAI_CODEX_CONTEXT_WINDOW,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		includedTools: ["apply_patch"],
		excludedTools: ["apply_diff", "write_to_file"],
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["low", "medium", "high", "xhigh", "max"],
		reasoningEffort: "low",
		inputPrice: 0,
		outputPrice: 0,
		supportsTemperature: false,
		displayName: "GPT-5.6 Sol",
		preferredIndex: 1,
		description: "Latest frontier agentic coding model via ChatGPT subscription",
	},
	"gpt-5.6-terra": {
		maxTokens: 128000,
		contextWindow: OPENAI_CODEX_CONTEXT_WINDOW,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		includedTools: ["apply_patch"],
		excludedTools: ["apply_diff", "write_to_file"],
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["low", "medium", "high", "xhigh", "max"],
		reasoningEffort: "medium",
		inputPrice: 0,
		outputPrice: 0,
		supportsTemperature: false,
		displayName: "GPT-5.6 Terra",
		preferredIndex: 2,
		description: "Balanced agentic coding model via ChatGPT subscription",
	},
	"gpt-5.6-luna": {
		maxTokens: 128000,
		contextWindow: OPENAI_CODEX_CONTEXT_WINDOW,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		includedTools: ["apply_patch"],
		excludedTools: ["apply_diff", "write_to_file"],
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["low", "medium", "high", "xhigh", "max"],
		reasoningEffort: "medium",
		inputPrice: 0,
		outputPrice: 0,
		supportsTemperature: false,
		displayName: "GPT-5.6 Luna",
		preferredIndex: 3,
		description: "Fast and efficient agentic coding model via ChatGPT subscription",
	},
	// kilocode_change end
	"gpt-5.5": {
		maxTokens: 128000,
		contextWindow: OPENAI_CODEX_CONTEXT_WINDOW,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		includedTools: ["apply_patch"],
		excludedTools: ["apply_diff", "write_to_file"],
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["low", "medium", "high", "xhigh"],
		reasoningEffort: "medium",
		// Subscription-based: no per-token costs
		inputPrice: 0,
		outputPrice: 0,
		supportsTemperature: false,
		description: "GPT-5.5: Proven previous-generation model via ChatGPT subscription",
	},
	"gpt-5.1-codex-max": {
		maxTokens: 128000,
		contextWindow: OPENAI_CODEX_CONTEXT_WINDOW,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		includedTools: ["apply_patch"],
		excludedTools: ["apply_diff", "write_to_file"],
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["low", "medium", "high", "xhigh"],
		reasoningEffort: "xhigh",
		// Subscription-based: no per-token costs
		inputPrice: 0,
		outputPrice: 0,
		supportsTemperature: false,
		description: "GPT-5.1 Codex Max: Maximum capability coding model via ChatGPT subscription",
	},
	"gpt-5.1-codex": {
		maxTokens: 128000,
		contextWindow: OPENAI_CODEX_CONTEXT_WINDOW,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		includedTools: ["apply_patch"],
		excludedTools: ["apply_diff", "write_to_file"],
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["low", "medium", "high"],
		reasoningEffort: "medium",
		// Subscription-based: no per-token costs
		inputPrice: 0,
		outputPrice: 0,
		supportsTemperature: false,
		description: "GPT-5.1 Codex: GPT-5.1 optimized for agentic coding via ChatGPT subscription",
	},
	"gpt-5.4": {
		maxTokens: 128000,
		contextWindow: OPENAI_CODEX_CONTEXT_WINDOW,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		includedTools: ["apply_patch"],
		excludedTools: ["apply_diff", "write_to_file"],
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["low", "medium", "high", "xhigh"],
		reasoningEffort: "medium",
		inputPrice: 0,
		outputPrice: 0,
		supportsTemperature: false,
		description: "GPT-5.4: OpenAI's flagship coding model via ChatGPT subscription",
	},
	// kilocode_change start: additional models in the current Codex account catalog
	"gpt-5.4-mini": {
		maxTokens: 128000,
		contextWindow: OPENAI_CODEX_CONTEXT_WINDOW,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		includedTools: ["apply_patch"],
		excludedTools: ["apply_diff", "write_to_file"],
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["low", "medium", "high", "xhigh"],
		reasoningEffort: "medium",
		inputPrice: 0,
		outputPrice: 0,
		supportsTemperature: false,
		displayName: "GPT-5.4 Mini",
		preferredIndex: 23,
		description: "Small, fast, and cost-efficient model for simpler coding tasks",
	},
	"gpt-5.3-codex-spark": {
		maxTokens: 128000,
		contextWindow: OPENAI_CODEX_CONTEXT_WINDOW,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		includedTools: ["apply_patch"],
		excludedTools: ["apply_diff", "write_to_file"],
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["low", "medium", "high", "xhigh"],
		reasoningEffort: "high",
		inputPrice: 0,
		outputPrice: 0,
		supportsTemperature: false,
		displayName: "GPT-5.3 Codex Spark",
		preferredIndex: 26,
		description: "Ultra-fast coding model via ChatGPT subscription",
	},
	// kilocode_change end
	"gpt-5.3-codex": {
		maxTokens: 128000,
		contextWindow: OPENAI_CODEX_CONTEXT_WINDOW,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		includedTools: ["apply_patch"],
		excludedTools: ["apply_diff", "write_to_file"],
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["low", "medium", "high", "xhigh"],
		reasoningEffort: "medium",
		inputPrice: 0,
		outputPrice: 0,
		supportsTemperature: false,
		description: "GPT-5.3 Codex: OpenAI's flagship coding model via ChatGPT subscription",
	},
	"gpt-5.2-codex": {
		maxTokens: 128000,
		contextWindow: OPENAI_CODEX_CONTEXT_WINDOW,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		includedTools: ["apply_patch"],
		excludedTools: ["apply_diff", "write_to_file"],
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["low", "medium", "high", "xhigh"],
		reasoningEffort: "medium",
		inputPrice: 0,
		outputPrice: 0,
		supportsTemperature: false,
		description: "GPT-5.2 Codex: OpenAI's flagship coding model via ChatGPT subscription",
	},
	"gpt-5.1": {
		maxTokens: 128000,
		contextWindow: OPENAI_CODEX_CONTEXT_WINDOW,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		includedTools: ["apply_patch"],
		excludedTools: ["apply_diff", "write_to_file"],
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["none", "low", "medium", "high"],
		reasoningEffort: "medium",
		// Subscription-based: no per-token costs
		inputPrice: 0,
		outputPrice: 0,
		supportsVerbosity: true,
		supportsTemperature: false,
		description: "GPT-5.1: General GPT-5.1 model via ChatGPT subscription",
	},
	"gpt-5": {
		maxTokens: 128000,
		contextWindow: OPENAI_CODEX_CONTEXT_WINDOW,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		includedTools: ["apply_patch"],
		excludedTools: ["apply_diff", "write_to_file"],
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["minimal", "low", "medium", "high"],
		reasoningEffort: "medium",
		// Subscription-based: no per-token costs
		inputPrice: 0,
		outputPrice: 0,
		supportsVerbosity: true,
		supportsTemperature: false,
		description: "GPT-5: General GPT-5 model via ChatGPT subscription",
	},
	"gpt-5-codex": {
		maxTokens: 128000,
		contextWindow: OPENAI_CODEX_CONTEXT_WINDOW,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		includedTools: ["apply_patch"],
		excludedTools: ["apply_diff", "write_to_file"],
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["low", "medium", "high"],
		reasoningEffort: "medium",
		// Subscription-based: no per-token costs
		inputPrice: 0,
		outputPrice: 0,
		supportsTemperature: false,
		description: "GPT-5 Codex: GPT-5 optimized for agentic coding via ChatGPT subscription",
	},
	"gpt-5-codex-mini": {
		maxTokens: 128000,
		contextWindow: OPENAI_CODEX_CONTEXT_WINDOW,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		includedTools: ["apply_patch"],
		excludedTools: ["apply_diff", "write_to_file"],
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["low", "medium", "high"],
		reasoningEffort: "medium",
		// Subscription-based: no per-token costs
		inputPrice: 0,
		outputPrice: 0,
		supportsTemperature: false,
		description: "GPT-5 Codex Mini: Faster coding model via ChatGPT subscription",
	},
	"gpt-5.1-codex-mini": {
		maxTokens: 128000,
		contextWindow: OPENAI_CODEX_CONTEXT_WINDOW,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		includedTools: ["apply_patch"],
		excludedTools: ["apply_diff", "write_to_file"],
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["low", "medium", "high"],
		reasoningEffort: "medium",
		inputPrice: 0,
		outputPrice: 0,
		supportsTemperature: false,
		description: "GPT-5.1 Codex Mini: Faster version for coding tasks via ChatGPT subscription",
	},
	"gpt-5.2": {
		maxTokens: 128000,
		contextWindow: OPENAI_CODEX_CONTEXT_WINDOW,
		supportsNativeTools: true,
		defaultToolProtocol: "native",
		includedTools: ["apply_patch"],
		excludedTools: ["apply_diff", "write_to_file"],
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["none", "low", "medium", "high", "xhigh"],
		reasoningEffort: "medium",
		inputPrice: 0,
		outputPrice: 0,
		supportsTemperature: false,
		description: "GPT-5.2: Latest GPT model via ChatGPT subscription",
	},
} as const satisfies Record<string, ModelInfo>
