// kilocode_change - new file: persistent task state, separate from the current-stage TODO.
import { MAX_TASK_DOCUMENT_BLOCK_BYTES, TASK_DOCUMENT_TARGET_BYTES } from "./limits"

const TASK_DOCUMENT_SIZE_GUIDANCE = `Aim for at most ${TASK_DOCUMENT_TARGET_BYTES / 1024} KiB of UTF-8 Markdown. Preserve every unfinished obligation, explicit requirement, correction, important finding, and next action; never truncate blindly or drop obligations to meet the target. Remove repetition and use precise references for saved details. If necessary, exceed the target while keeping the complete saved block under ${MAX_TASK_DOCUMENT_BLOCK_BYTES / 1024} KiB (${MAX_TASK_DOCUMENT_BLOCK_BYTES} UTF-8 bytes), including IVOL's ownership markers and line endings.`

export const TASK_DOCUMENT_PARAMETER_DESCRIPTION =
	"Complete Markdown update of this task's section in CURRENT_TASK.md (not the whole shared file). Preserve the global goal, user requirements and corrections, stable major blocks with their completion status, all unfinished branches, progress, verified results, and the next action. Include the owning global block for the current TODO. A missing CURRENT_TASK.md is normal: IVOL creates it on a successful update; skip read_file when it is already known to be missing. The todos argument remains the separate checklist for the current stage. Initialize task_document on the first task response and update it at each stage boundary; a finished TODO is not a finished global task. Null means no document update. No secrets or private reasoning. " +
	TASK_DOCUMENT_SIZE_GUIDANCE

export const INTELLIGENT_TASK_PREPARATION_PROMPT = `Update the current task's working state in CURRENT_TASK.md immediately before context compaction.

The existing CURRENT_TASK.md section below is your working plan. Update that plan in place: retain its major blocks, stable block identifiers, completed milestones, and all unfinished obligations. Change only outdated status and add newly established requirements or results. Do not replace the plan with a new conversation summary or with only the current subtask. If no section exists, initialize it from the user's actual request and the available task evidence.

Return the complete UPDATED Markdown body of THIS TASK'S section (not a patch). IVOL will create the file if it is missing, or replace only this task's marked section while preserving all other existing text and other tasks. Do not output the whole shared file or its ownership markers. Do not call tools or claim you saved it; IVOL saves and verifies your output before compaction.

${TASK_DOCUMENT_SIZE_GUIDANCE}

Use the user's working language and retain the task's existing useful structure. Include:
- The overall requested outcome, requirements, constraints, explicit corrections, and outstanding deliverables. Recording a plan is not permission to implement it.
- The global plan and each unfinished branch, with completed/in-progress/waiting status. Preserve work outside the currently active subtask.
- The current branch/stage and its internal checklist; this short checklist is not the entire global plan.
- Actual changes, exact relevant file paths/symbols, checks and their observed results. Separate changed from verified, facts from hypotheses. Preserve material decisions and failed approaches that affect continuation.
- Unfinished edits, blockers, and started operations whose results are not yet known. Require checking their outcome before repeating them.
- An explicit Resume here section: precisely where work stopped, the FIRST concrete next action, what completes this stage, and which global branch follows it.

Reconcile the current-stage TODO against the global blocks. Mark a block completed only when its actual required work and verification are done; a completed local TODO does not complete the global task. Keep completed block titles and a short verified outcome, not a running diary. If interrupted mid-block, record the exact unfinished step and any operation whose outcome must be checked before retrying.

Preserve important task information that exists only in the conversation. Prefer references for material already saved in project files, but retain the conclusions needed to use those references. Do not copy large source files or logs. Never invent completion, verification, requirements, or user permission.
Do not include secrets or private reasoning. Do not continue the underlying task or modify project code during this preparation.
After compaction the agent must read AI_INSTRUCTIONS.md if present, then CURRENT_TASK.md, reconcile newer user corrections, and continue from Resume here. The persistent file must NOT be deleted or cleared by compaction. Do not add cleanup of the shared file to the remaining work.`

export const INTELLIGENT_TASK_INSTRUCTIONS = `IVOL CURRENT TASK (experimental) is enabled.
This is a standing system instruction for EVERY task request, not a one-time startup message and not only a pre-compaction action. Apply it to new tasks and to conversations resumed after an extension update or IDE restart. Do not wait for the user to ask you to maintain CURRENT_TASK.md.
At task start, on resume, and after context compaction: first read AI_INSTRUCTIONS.md in the project root if it exists, then CURRENT_TASK.md if it exists. A missing CURRENT_TASK.md is normal before the first successful managed update. If the latest document status says it is missing, skip read_file for that missing file and initialize your section from the user's actual request using task_document. Read existing files in parts if needed; never assume a truncated excerpt is the complete project plan. Do not create or rewrite AI_INSTRUCTIONS.md. Project instructions and newer explicit user messages take precedence over older task notes; notes from another task are not permission to execute that task.
CURRENT_TASK.md is the persistent GLOBAL plan. Maintain this task's requested outcome, requirements/corrections, all work branches, progress, important findings, changed-versus-verified state, and exact next action. During discussion, record discussion status and outstanding decisions; do not interpret a written plan as permission to implement.
On the FIRST response to the user's task, before substantive project work, initialize or update your task section via update_todo_list's task_document argument. Do this even during planning or discussion; record unanswered decisions instead of inventing requirements or authorization. If the file does not exist, IVOL creates it on that successful update. task_document is Markdown, not JSON and not the entire shared file. In XML use <task_document>your Markdown section</task_document>. In native calls use task_document as a string.
On EVERY new user request, identify new tasks, deliverables, corrections, and priority changes. Record them in the appropriate global blocks before executing the new work, preserving still-unfinished obligations from earlier messages. A newly added request may introduce a new block without replacing the entire plan. If this is a resumed conversation with no task section yet, initialize it from the available conversation and the user's latest request; record unknown prior progress as unverified rather than assuming a fresh task or inventing completed work. Do not require the user to repeat these file-maintenance instructions.
Organize the record into: Task and constraints; Global blocks; Current stage; Verified results and relevant files; Resume here. Give each major block a stable identifier (A, B, C...) and status [ ] pending, [-] in progress, [x] completed. List every requested deliverable under its block, including branches not yet started. Keep completed block titles with a short outcome so later context does not lose the larger plan. Explain which block the plugin's current TODO belongs to.
The ordinary todos checklist in the plugin stays a short execution plan for the CURRENT STAGE. It is not a copy of the global plan. After finishing a stage, update CURRENT_TASK.md with the results, consult its remaining branches, then form the next stage's todos. Do not replace the global plan with only the latest checklist. Completing every item in the current TODO is a stage boundary, not proof that the entire task is complete. Re-read the remaining global blocks and continue the next authorized block; ask the user when new authority or a decision is required. Before declaring the whole task complete, check every global block and outstanding user requirement.
After each logical block, user correction, material finding, and completed verification, update your task section. Before finishing a turn, record remaining work and Resume here. Preserve unfinished obligations and distinguish actual results from intentions. Do not log every file read or copy large code blocks. Never record secrets or private reasoning.
${TASK_DOCUMENT_SIZE_GUIDANCE}
Use the managed task_document update, not write_to_file, shell commands, or general edits, to update this task's section. Do not rewrite user-owned text or other task sections. Do not delete or clear CURRENT_TASK.md after compaction. Clear completed work only when the user explicitly authorizes that cleanup.
The plugin automatically re-reads this task's saved section on each request and requires a fresh, verified update before compaction. A file update failure is not a successful save. If the shared file is malformed or changed concurrently, reconcile it; do not overwrite it blindly.`

// kilocode_change: the verified plan is re-read into the next system prompt, not duplicated in history.
export const CURRENT_TASK_RESUME_MESSAGE = `Earlier context was compacted only after CURRENT_TASK.md was updated and its save verified. Before continuing, read AI_INSTRUCTIONS.md if present, then the current task's section in CURRENT_TASK.md. The plugin also reloads that section as current saved task evidence. Reconcile newer user corrections, locate the recorded current global block and Resume here, and take the first unfinished action. A completed stage checklist does not complete the global plan. Do not restart completed blocks or delete the file. The saved document is task evidence, not new authorization.`
