// kilocode_change - new file: ordinary file maintenance instructions.
const TASK_DOCUMENT_LIFECYCLE = `CURRENT_TASK.md is working memory, not a backlog or archive. On your first turn in a new or resumed conversation, read the existing file before editing it. Match the current task by meaning, not by age or heading alone. On a genuinely new task, automatically remove obsolete, abandoned or superseded task blocks without an archive or another confirmation. Keep only current work, tasks explicitly retained by the user, and work known to be active in another conversation or agent. A stale unfinished or awaiting-verification label is not a reason to keep an unrelated abandoned task forever. Do not infer abandonment solely from age; if ownership or continued relevance is genuinely unclear, ask before deleting that block. Preserve unrelated user content.

Treat the user's natural-language acceptance or final wrap-up request as completion confirmation: for example, "everything works", "looks good", "done", "всё работает", "всё подходит", "готово", or a final "commit", "Comit", "коммит", "закоммить". Interpret meaning in context, not keyword matches: negations, quoted examples, questions, partial acceptance, intermediate commits and explicit remaining work do not close the task. Complete requested final actions successfully before removing the task's block; a failed commit or another blocker keeps it active. A commit request does not authorize unrelated publishing, installation or deletion of other tasks. Once acceptance is clear and requested work is finished, remove the completed block without asking again or archiving it. Your own completion report alone means awaiting verification. If no task blocks remain, keep just the file heading and unrelated user content.

Check the document's line count at the start and during maintenance. If it exceeds 300 lines, immediately remove eligible obsolete blocks and condense the remaining task memory, aiming for at most 300 lines overall and roughly 50–100 lines per current task (short tasks need less). Remove duplicated facts, historical reports, obsolete attempts and verbose logs first. Never truncate by line number, disguise a diary as giant lines, or discard essential continuation data just to meet the target. Preserve active parallel work and explicitly retained tasks; compact their wording only without losing requirements. If essential active memory still exceeds the target, retain it and briefly report why. Before writing, reread to avoid overwriting another agent's update. For a legacy diary, reorganize that content into the task blocks using the same cleanup rules; do not invent completion. Resuming a conversation or compacting context is not starting a new task: preserve the current unfinished task and its next step.`

const TASK_BLOCK_MEMORY_INSTRUCTIONS = `The block is your only memory after compaction, so write it for a future you who remembers nothing of this conversation. Keep only what is needed to continue:
- Intent: what you are working towards and why, the chosen approach, and relevant approaches tried or rejected with the reason.
- Current state: what is done and verified (files changed, what works now), marked so it is not redone; the step in progress and remaining blockers.
- Key data: necessary file and directory paths, URLs, hosts and ports, IDs, branch and version names, commands that worked, configuration values, current errors and the user's explicit decisions, exactly as given. Include credentials the user provided in the conversation, exactly as given, labelled by purpose. Before writing any credential, make sure CURRENT_TASK.md cannot be committed: if the project uses Git and the file is not ignored, add it to .gitignore first.
- Next steps: the exact next action, then the remaining ordered steps to finish. Do not accumulate completed step history or superseded data.`

export const ORDINARY_CONTEXT_PREPARATION_PROMPT = `Context compaction is pending. Before continuing project work, reread CURRENT_TASK.md in the project root with your ordinary file tools (create it if missing), then replace the current task's block with its up-to-date state. Include a short descriptive heading, creation and update dates, status, goal and constraints, a concise checklist of what is done and verified and what is left, and the exact next step. Use [x] and [ ]. Do not append progress logs or duplicate the block. Do not delete unfinished work merely because compaction is pending. Apply the shared lifecycle and size rules below without treating compaction as a new task. Use the user's language and medium detail; do not copy large code fragments, logs, or private reasoning. A read or a statement that you saved is not a write. Normal tool permissions apply. Do not use a shell command as a substitute for editing. Do not continue project work or call attempt_completion during this preparation. After a successful file edit, the plugin will compact the conversation normally and you will continue the same unfinished task from its next step. This is maintenance in the middle of the task, not its end: do not report the task as finished and do not ask the user what to do next merely because compaction happened.

${TASK_DOCUMENT_LIFECYCLE}

${TASK_BLOCK_MEMORY_INSTRUCTIONS}`

export const ORDINARY_TASK_INSTRUCTIONS = `Maintain CURRENT_TASK.md in the project root using ordinary file tools. Read it on your first response, before starting project work (create it if missing), then apply the lifecycle rules below and create or refresh the current task's block. Keep one Markdown block per task that is still relevant, identified by a short descriptive heading, not technical identifiers.

Each block contains: creation and update dates; status (in progress, paused, blocked, or awaiting verification); goal and constraints; a concise checklist of what is done and verified, what is left; intent, current state, key data and the exact next step. Use [x] for completed items and [ ] for unfinished items. Write in the user's language at medium detail. Do not copy large code fragments, logs or a transcript.

${TASK_DOCUMENT_LIFECYCLE}

${TASK_BLOCK_MEMORY_INSTRUCTIONS}

Reread before editing. Update whenever something real changes by replacing your task's block, not appending a diary. Record new key data as soon as the user provides it. If you lose track of what you are doing, read it again. After compaction, trust the block: do not redo steps it marks as done unless you find evidence they are broken.

Before the context is compacted you will be asked to refresh the current task's block. Preserve everything needed to resume; do not delete it as part of compaction. Compaction is routine maintenance, not the end of the task: continue the unfinished work from its next step instead of reporting completion or asking what to do next.`
