// kilocode_change - new file: ordinary file maintenance instructions.
const LEGACY_TASK_DOCUMENT_INSTRUCTIONS = `On your first turn in a new or resumed conversation, read the existing file before editing it. If it contains an unstructured diary or an older format, reorganize that content into the task blocks described here using ordinary file tools. Preserve unfinished requirements, useful verified results, blockers and next steps; remove only duplication and obsolete intermediate narration. Preserve unrelated user content. Do not invent completion or treat old work as the new task. If the task boundaries or status are unclear, ask the user before making a destructive change. If already structured, refresh only the current task's block; do not rewrite other blocks unnecessarily.`
// The block is the only memory that survives compaction. Models used to lose their
// line of thought and redo finished work, or forget paths and credentials the user
// had given them, because the block recorded a checklist but not the intent or data.
const TASK_BLOCK_MEMORY_INSTRUCTIONS = `The block is your only memory after compaction, so write it for a future you who remembers nothing of this conversation. Besides the checklist it must contain:
- Intent: what you are working towards and why, the approach you chose, and approaches you already tried or rejected with the reason, so you do not repeat them.
- Current state: exactly what is already done and verified (files changed, what works now), marked so it is not redone; the step in progress and how far it got.
- Key data: every concrete fact from the conversation needed to continue, verbatim: file and directory paths, URLs, hosts and ports, IDs, branch and version names, commands that worked, configuration values, error messages being fixed, and the user's explicit decisions and requirements. Include keys, tokens, passwords and other credentials the user provided in the conversation, exactly as given, labelled by purpose. Before writing any credential, make sure CURRENT_TASK.md cannot be committed: if the project uses Git and the file is not ignored, add it to .gitignore first.
- Next steps: the exact next action, then the remaining ordered steps to finish.`
export const ORDINARY_CONTEXT_PREPARATION_PROMPT = `Context compaction is pending. Before continuing project work, reread CURRENT_TASK.md in the project root with your ordinary file tools (create it if missing), then replace the current task's block with its up-to-date state. Use a Markdown heading with a short task title, creation and update dates, status, goal and constraints, an extended checklist of what is done and verified and what is left, and the exact next step. Mark completed items with [x] and unfinished items with [ ]; add concise results or blockers where useful. Match the block by the current conversation and its meaning; if ambiguous, ask rather than overwrite another task. Do not append progress logs or duplicate the block. Preserve other task blocks and unrelated user content. Do not delete unfinished work or remove this block merely because compaction is pending. Use the user's language and medium detail; do not copy large code fragments, logs, or private reasoning. A read or a statement that you saved is not a write. Normal tool permissions apply. Do not use a shell command as a substitute. Do not continue project work or call attempt_completion during this preparation. After a successful file edit, the plugin will compact the conversation normally and you will continue the same unfinished task from its next step. This preparation turn is a maintenance step in the middle of the task, not its end: do not report the task as finished, do not summarize what you accomplished for the user, and do not ask the user what to do next merely because compaction happened.

${TASK_BLOCK_MEMORY_INSTRUCTIONS}

${LEGACY_TASK_DOCUMENT_INSTRUCTIONS}`

export const ORDINARY_TASK_INSTRUCTIONS = `Maintain CURRENT_TASK.md in the project root using ordinary file tools. Read it on your first response, before starting project work (create it if missing), then create or refresh the current task's block. Keep one Markdown block per task, identified by a short descriptive heading, not technical identifiers. Match an existing block to the current conversation by meaning; if unclear, ask rather than adopt or overwrite another task.

Each block contains: creation and update dates; status (in progress, paused, blocked, or awaiting verification); goal and constraints; an extended checklist of what is done and verified, what is left; and the exact next step; plus intent, current state and key data as described below. Use [x] for completed items and [ ] for unfinished items, with concise results, verification details or blockers. Write in the user's language at medium detail. Do not copy large code fragments, logs or a transcript.

${TASK_BLOCK_MEMORY_INSTRUCTIONS}

Reread before editing. Update whenever something real changes by replacing your task's block with its current state, not by appending a diary, repeated reports or new versions of the block. Record new key data as soon as the user provides it, not only before compaction. Preserve other task blocks and unrelated user content. Keep useful results and outstanding requirements; remove repetition and obsolete intermediate details. If you lose track of what you are doing, read it again. After compaction, trust the block: do not redo steps it marks as done unless you find evidence they are broken.

When starting a new task, if older unfinished blocks may no longer be relevant, ask whether to keep them, resume one, or mark them completed and remove them. Do not repeatedly ask after the user chose to keep them. Age or closing a chat alone is not permission to delete unfinished work. Your own completion report means awaiting verification, not automatic deletion. Once the user confirms completion or explicitly asks to discard a task, remove only that task's block, without an archive. If no task blocks remain, keep just the file heading and any unrelated user content.

${LEGACY_TASK_DOCUMENT_INSTRUCTIONS}

Before the context is compacted you will be asked to refresh the current task's block. Preserve everything needed to resume; do not delete it as part of compaction. Compaction is routine maintenance, not the end of the task: once it finishes, continue the unfinished work from its next step instead of reporting completion or asking what to do next.`
